"""fix: relations city and temperature models

Revision ID: 26c1a0d9e10a
Revises: a3a8c0ebb03d
Create Date: 2026-03-06 11:02:18.805144

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "26c1a0d9e10a"
down_revision: Union[str, Sequence[str], None] = "a3a8c0ebb03d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
