"""fix: rename fields and city have a lot of temperatures models

Revision ID: 5dd1006f8b6f
Revises: a4692573e4c6
Create Date: 2026-03-06 14:43:31.669038

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5dd1006f8b6f'
down_revision: Union[str, Sequence[str], None] = 'a4692573e4c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('city', sa.Column('additional_info', sa.String(length=511), nullable=True))
    op.drop_column('city', 'description')
    op.add_column('temperature', sa.Column('date_time', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
    op.drop_index(op.f('ix_temperature_city_id'), table_name='temperature')
    op.create_index(op.f('ix_temperature_city_id'), 'temperature', ['city_id'], unique=False)
    op.drop_column('temperature', 'data_time')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('temperature', sa.Column('data_time', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
    op.drop_index(op.f('ix_temperature_city_id'), table_name='temperature')
    op.create_index(op.f('ix_temperature_city_id'), 'temperature', ['city_id'], unique=1)
    op.drop_column('temperature', 'date_time')
    op.add_column('city', sa.Column('description', sa.VARCHAR(length=511), nullable=True))
    op.drop_column('city', 'additional_info')
    # ### end Alembic commands ###
