"""chore: add unique constraint to city_id

Revision ID: 8540a1bc7bda
Revises: cdbcb8e4dde0
Create Date: 2026-03-06 10:48:21.797819

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "8540a1bc7bda"
down_revision: Union[str, Sequence[str], None] = "cdbcb8e4dde0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_temperature_city_id"), table_name="temperature")
    op.create_index(
        op.f("ix_temperature_city_id"), "temperature", ["city_id"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_temperature_city_id"), table_name="temperature")
    op.create_index(
        op.f("ix_temperature_city_id"), "temperature", ["city_id"], unique=False
    )
    # ### end Alembic commands ###
