"""chore: rename temperatures to temperature in city field

Revision ID: a3a8c0ebb03d
Revises: 8540a1bc7bda
Create Date: 2026-03-06 10:55:04.386613

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "a3a8c0ebb03d"
down_revision: Union[str, Sequence[str], None] = "8540a1bc7bda"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
