"""fix: relations city and temperature models

Revision ID: a4692573e4c6
Revises: 26c1a0d9e10a
Create Date: 2026-03-06 11:04:39.376339

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "a4692573e4c6"
down_revision: Union[str, Sequence[str], None] = "26c1a0d9e10a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
