"""add back relation temperatures in city model

Revision ID: cdbcb8e4dde0
Revises: 175ebb0821f8
Create Date: 2026-03-05 20:27:59.756821

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cdbcb8e4dde0'
down_revision: Union[str, Sequence[str], None] = '175ebb0821f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
